const payload = [
  {
    id: 0,
    name: 'Malibu Beach',
    hash: 'malibu-beach',
    country: 'USA',
    city: 'California',
    airline: 'American Airlines',
    distance: 5243,
    timeMinutes: 1585,
    price: 2500,
    roundTrip: true,
    airlineLocationImage: '/img/Sleep-Image.png',
  },
  {
    id: 1,
    name: 'Airlie Beach',
    hash: 'airlie-beach',
    country: 'Australia',
    city: 'Queensland',
    airline: 'Virgin Australia',
    distance: 7065,
    timeMinutes: 1385,
    price: 1976,
    roundTrip: true,
    airlineLocationImage: '/img/Travel_Image.png',
  },
  {
    id: 2,
    name: 'Cloud Nine',
    hash: 'cloud-nine',
    country: 'Philippines',
    city: 'Siargao',
    airline: 'Philippine Airlines',
    distance: 6573,
    timeMinutes: 1185,
    price: 1376,
    roundTrip: false,
    airlineLocationImage: '/img/Sleep-Image.png',
  },
  {
    id: 3,
    name: 'Vieux Boucau',
    hash: 'vieux-boucau',
    country: 'France',
    city: 'Hossegor',
    airline: 'Air France',
    distance: 2573,
    timeMinutes: 685,
    price: 425,
    roundTrip: true,
    airlineLocationImage: '/img/Travel_Image.png',
  },
];

export default payload;
